verbose: true
instrumentation:
   excludes: ['spec/*Spec.js', 'spec/runBackendTests.js',
                '**/bower_components/**', 'karma.conf.js',
                'private/js/*.js', 'coverageFrontEnd/**']
   include-all-sources: true